### ISSUE TITLE
Path flips sometimes.

### ISSUE THREAD

**Issue by dizhongzhu** [mhogg/pygeodesic#1]
Thanks for sharing the code!
When I call the function geoalg.geodesicDistance(p1, p2), where p1 should be source, p2 shoulde be target. The returned path will be flipped sometimes. i.e. The path should start from p1 to p2, but instead it will return a path from p2 to p1 instead.

**Comment by mhogg** [comment]
Hi @dizhongzhu

pygeodesic is a wrapper around existing C++ code. But looking at the C++ code, I can see that you are right. The C++ code creates the path by performing a trace from the target back to the source. So I guess the order of points in the path is reversed. 

It might be more intuitive to reverse the path points returned by pygeodesic. What do you think?
