### ISSUE TITLE
Issue when importing pygeodesic

### ISSUE THREAD

**Issue by louisdhb** [mhogg/pygeodesic#2]
Hello, 
Thank you for the nice library. However, I cannot import it as I get the following:

```
import pygeodesic.geodesic as geodesic

  File "pygeodesic\geodesic.pyx", line 1, in init pygeodesic.geodesic

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

Any idea ?

**Comment by mhogg** [comment]
Hi @louisdehaybe,
You need to give some more info. How did you install pygeodesic? What version of Python are you using? What OS are you on? Anything else that may be relevant.

**Comment by louisdhb** [comment]
Hi, 

Sure sorry. I'm using an anaconda environment with python 3.8.12, on windows 10. I simply installed with pip install pygeodesic.

**Comment by akaszynski** [comment]
This issue is likely due to the build version used with numpy. Quite likely it wasn't built with the [oldest-supported-numpy](https://pypi.org/project/oldest-supported-numpy).
